### ISSUE TITLE
Make EPEL repo install optional

### ISSUE THREAD

**Issue by aamerik** [edestecd/puppet-clamav#1]
Hi! Is it possible to toggle epel repo management? Seems like epel gets installed no matter what on RHEL.  My environment already has a local Satellite 6 EPEL mirror.
Thanks

**Comment by edestecd** [comment]
This is currently not possible, but I can see why you would want this.
I can make a manage_repo option.  I should have some time later this morning.

**Comment by edestecd** [comment]
You should now be able to do this to turn off epel management:

``` puppet
class { 'clamav':
  manage_repo => false,
}
```

**Comment by edestecd** [comment]
I have another fix to make, then I will publish to the forge...

**Comment by aamerik** [comment]
Thank you sir!

**Comment by edestecd** [comment]
Should be on the forge now...
