### ISSUE TITLE
Add ability to set the clam daemons as running or stopped

### ISSUE THREAD

**Issue by bschonec** [edestecd/puppet-clamav#13]
Currently "running" is the only option for clam and freshclam.  While it may not make sense in a lot of environments not to have these running, in _my_ environment, I don't have both daemons running.  It'd be nice to be able to specify running or not:

  service { 'clamd':
28      ensure     => running,
29      name       => $clamd_service,
30      enable     => true,
Puppet
manifests/freshclam.pp 

32    if $freshclam_service {
33      service { 'freshclam':
34        ensure     => running,
35        name       => $freshclam_service,

**Comment by edestecd** [comment]
I'm open to making the running a parameter that you can change.
Just put running in the params.pp as the default and accept a param, similar to how $clamd_service is set.

I'd accept a pull request that does that...

**Comment by bschonec** [comment]
I'm working on that now...

**Comment by edestecd** [comment]
Cool, looking forward to it.
I need some new features to make the next release on the forge ;)

**Comment by bschonec** [comment]
Please bear with me.  I am not a developer by trade, have only a year or so
of Puppet experience and have no idea [yet] how to make puppet test
configurations.

**Comment by edestecd** [comment]
Great...  Its an excellent opportunity to learn.  I'm always glad to help.

**Comment by edestecd** [comment]
Closed with merge #14

**Comment by edestecd** [comment]
Closed with merge #14
