### ISSUE TITLE
Is there a way to comment out an option in clamd.conf?

### ISSUE THREAD

**Issue by ubellavance** [edestecd/puppet-clamav#18]
I'd like to comment out the LogFile option in clamd config file. I looked at the template file, but I don't know what the .delete means or how it can be called.

Thanks,

**Comment by edestecd** [comment]
Can you just set it to the default instead, which would be the equivalent of commenting it out...

**Comment by edestecd** [comment]
Another option is to check for explicit undef and not set those options.
I think that may be one of the next features I add along with making both RedHat and Ubuntu use the same hash loop for the config file.

**Comment by ubellavance** [comment]
The default of this setting is "disabled". I don't think I can set that.

**Comment by edestecd** [comment]
I should be able to fix this in the next version.
I will be adding RedHat 7 support as well as refactoring how the template is rendered as mentioned above.  The mysql module checks the options hash for explicit undef and removes those options.  I will prob do it that way.

**Comment by edestecd** [comment]
Example code that would work for you after I make the change:

``` puppet
class { 'clamav':
  manage_clamd      => true,
  manage_freshclam  => true,
  clamd_options     => {
    'LogFile' => undef,
  },
}
```

**Comment by edestecd** [comment]
@ubellavance this should work for you now.  Are you able to check out master and give it a try?

**Comment by ubellavance** [comment]
I tried running with all the defaults and it need to have either a LocalSocket or a TCPSocket. I think the best would be to set a `LocalSocket /var/run/clamd.scan/clamd.sock`. If I define it manually, clamd starts and seems to work OK. Looks good so far!  I see that by moving to the use of hashes we loose all the description of the config options in the config file but I guess it's the price to pay to have a simpler method of file generation.  I should be doing more extensive testing next week (I haven't checked freshclam much).

**Comment by edestecd** [comment]
I agree about the LocalSocket.  I originally pulled the defaults from the default config file, but I may do some tweaking to make it work out of the box.  RedHat 7 is even worse.  There are literally no options set in that default config file.

Yes, using only a hash cans all the comments...  That is the way the stock ubuntu config comes, so we were doing that for ubuntu before...  Most other official modules from the forge take this approach.  You always have the online doc and shouldn't be logging into servers anyway...

**Comment by ubellavance** [comment]
Agreed.  I would simply make sure that the clamd service runs out of the box.
