### ISSUE TITLE
Error during puppet run

### ISSUE THREAD

**Issue by ascott97** [edestecd/puppet-clamav#29]
Hi,

I am recieving this error during puppet run:

Error: Could not unmask clamav:
Error: /Stage[main]/Clamav::Clamd::Service/Service[clamav::clamd]/ensure: change from stopped to running failed: Could not unmask clamav:

I'm unsure whether this a bug or my configuration, any advice greatly appreciated.

**Comment by edestecd** [comment]
Can I get some details:
1. What OS/Version are you using?
2. A paste of your code / profile would also be helpful

**Comment by ascott97** [comment]
OS: Centos 7.2-1511

## Hiera:

role: 'roles::clamav_test'

clamav::manage_clamd: true
clamav::manage_freshclam: true

clamav::freshclam_options:
  LogTime: yes
  LogFileMaxSize: '5'
  DatabaseMirror:
- clam-mirror.mydomain

Profile:
class profiles::clamav_test {
  include clamav
}

**Comment by edestecd** [comment]
Can you try

``` yaml
clamav::manage_user: true
```

The only thing I can think of is that the user / group is missing.

**Comment by edestecd** [comment]
@ascott97 are you still having this issue?
