### ISSUE TITLE
Convert to Puppet 4 conventions

### ISSUE THREAD

**Issue by edestecd** [edestecd/puppet-clamav#49]
Use a puppetlabs module as an example and for god sakes use module sync!

**Comment by pillarsdotnet** [comment]
I'm working on this, and also adding support for Windows.

**Comment by edestecd** [comment]
WOW! thanks. I was planning on getting to this eventually, but would be very appreciative if you did it :smile:

**Comment by edestecd** [comment]
I need to get back to #38 also... I'll try and get to that tomorrow

**Comment by pillarsdotnet** [comment]
Good info here: https://docs.puppet.com/puppet/5.3/hiera_migrate_modules.html

**Comment by pillarsdotnet** [comment]
Started work [here](https://github.com/pillarsdotnet/puppet-clamav/tree/puppet4).

Not done by a long shot.

**Comment by edestecd** [comment]
Cool. I'm all for using hiera 5 instead of params.pp. I hate reading through that mess. ITs nice to finally have a good alternative.

**Comment by edestecd** [comment]
I'm all for doing work in small chunks. Can you make a separate issue/PR for adding Windows.
