### ISSUE TITLE
Hash iteration order in a template not consistent 

### ISSUE THREAD

**Issue by bergkatten** [edestecd/puppet-clamav#5]
Hi,
The module is really working great and I only have a small issue:

The configuration file /etc/clamav/freshclam.conf is every second time changing. The parameters have the same values but the order inte the created file based on the template does not "settle". 
This makes machines their configurations continuoly changing. 

I've tested this code change on Ubuntu and it sorts the file contents by the first key. 
Testing was dome with 3.4.3.

The change was done in  freshclam.conf.Debian.erb.

-<% @config_options.each do |k,v| -%>
+<% @config_options.sort.each do |k,v| -%>
Cheers,
/István

**Comment by edestecd** [comment]
Yes, I have seen this done in other modules.
Are you using ruby 1.8.7?
1.8.7 does not preserve hash order, however newer ruby versions preserve hash order.

**Comment by bergkatten** [comment]
Hi,

On the puppet master we use 1.8.7, 
On the clients it changing most of them run 1.9.3 and some 1.8.7 but all have this issue.
I suppose this is a server side issue then. Hiera is on the server side and that may be too old. 

Maybe I should fork the module on github until we upgrade the master. 

Cheers,
/István

**Comment by edestecd** [comment]
Yes, the master compiles the template into the catalog, so the masters ruby version is in play here.

I don't mind making this change and releasing a new version.
We should support 1.8.7, since some still use it.

Are you comfortable forking and making a pull request?  If not, I can make the change.

**Comment by bergkatten** [comment]
Hi,
If you released a version that would be great! I need to get more comfy with this web interface... :)
Only used git on command line until now. 
Cheers,
/István

**Comment by edestecd** [comment]
No problem, I will make the change.  It should be up today.

**Comment by edestecd** [comment]
This fix is included in 0.3.0, which is now on the forge.

**Comment by bergkatten** [comment]
Hi,
Super! 
Thank you!
/István
