### ISSUE TITLE
ERROR: Can't save PID to file /var/run/clamav/freshclam.pid: Permission denied

### ISSUE THREAD

**Issue by hdep** [edestecd/puppet-clamav#52]
Hello,

I'm running you plugin on debian 8. just figure out that freshclam can't create the pid file  into /var/run/clamav/. this folder is owned by root and freshclam run a user clamav.

Anyway this isn't needed when we use systemd according to : 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804132

I checked this PR : 
https://github.com/edestecd/puppet-clamav/pull/38/commits

Does this fixed also this issue ?

**Comment by edestecd** [comment]
Yes I think it does. I was close to merging that at one point. I need to look at it again. I think he fixed everything.

**Comment by hdep** [comment]
great. 
Thank you for the feed back.

**Comment by roock** [comment]
Would be great to  have that merged, we are also affected by this issue (freshclam pid file cannot be created on Debian 8+)
