### ISSUE TITLE
Move this module to voxpupuli

### ISSUE THREAD

**Issue by hdep** [edestecd/puppet-clamav#61]
Since you mentioned being swarmed with work, maybe we can move this module to voxpupuli so more eyes can keep it up to date and I think this module is usefull for the community.

https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli

What do you think  ?

**Comment by slauger** [comment]
I totally agree with @hdep... maybe it's also possible to switch from the GPL license to e.g. MIT or Apache.

**Comment by ubellavance** [comment]
Hi @edestecd, this issue has been opened for more than one year. Can you please consider moving this module to voxpupuli?

**Comment by edestecd** [comment]
We upgraded to puppet 5 finally so we had the need to make updates. Sorry for the delay.
