### ISSUE TITLE
freshclam broken on RHEL8

### ISSUE THREAD

**Issue by flinkflonk** [edestecd/puppet-clamav#69]
The freshclam service is not run by cron (as mentioned in freshclam.pp), så systems end up with the signatures from installation time or no signatures at all.

Reason for that is that the service as coming from the epel is set to disabled, *and* it's named clamav-freshclam, not freshclam (as the module assumes).

That means freshclam_service_enable and freshclam_service_ensure don't have the expected effect when set.

Solution: make the service name a variable that depends on OS version and major, and set it to clamav-freshclam in RHEL8, then use that as the service name instead of the hard-coded string "freshclam".

**Comment by edestecd** [comment]
Sounds like a great idea to me. Thanks for the input on CentOS 8. Now we just need a PR to implement it.

**Comment by edestecd** [comment]
#70
