### ISSUE TITLE
Module Design

### ISSUE THREAD

**Issue by jlambert121** [edestecd/puppet-clamav#8]
I was looking at using this module and decided it needed some tests so was going to write them.  As I looked at the module in more detail all of your subclasses inherit clamav::params and set the defaults from there, but it appears this module is intended to be called from the main class and override any defaults there.  How do you intend this module to be used?  Main class and set params or call each subclass individually?

**Comment by edestecd** [comment]
@jlambert121, it would be great to have some tests.  This has always been on my list of to dos going forward.

I generally intend it to be used from the main class only and this is really the only way I have used it.

That being said, it could also be used by calling the subclasses, the way it is currently written.
So I guess right now it supports both.  This could be a pain going forward, as you have to pass each parameter through the main class.

I'm open to suggestions for going either way.  Supporting both can be confusing and overly complex.  What are your thoughts?

**Comment by jlambert121** [comment]
I used to do with my modules similar to what you have, but it seemed to be harder to maintain as my modules got more complex.  Normally I like to control everything through the main class, it lets me validate in one place and do any logic that is used between classes.  I've gone so far as to fail on some modules if a "private" class is called directly (https://github.com/evenup/evenup-sssd/blob/master/manifests/install.pp#L13).  My vote is to only support going through the main class, but I didn't want to change that and send you a PR if that's not how you wanted your module.

**Comment by edestecd** [comment]
I have seen lots of the supported modules follow this pattern of having private sub classes.
It seems practical.  Many of my newer/more complex modules do this as well to avoid making me type every parameter over and over.  The sub classes just use the variables scoped to the parent class and don't have their own parameters.

``` puppet
class clamav (
  $clamd_package = $clamav::params::clamd_package,
) inherits clamav::params {
  include clamav::clamd
}

class clamav::clamd {
  package { 'clamd':
    ensure => installed,
    name   => $clamav::clamd_package,
    before => File['clamd.conf'],
  }
}
```

I'm cool with that, if you want to submit a PR doing that.  I've had at least one issue with someone trying to use both the main class and the subclasses...

If you can, please make a separate branch and PR for this change and then another for the tests.
And thanks for any contributions you make ;)
